In [5]:
import numpy as np
import random

In [7]:
np.random.normal(10,2,(7,4))

array([[ 9.59073272, 10.7320234 , 10.36333946,  9.04504049],
       [11.42306155,  8.18596213, 11.50309484, 13.17831171],
       [ 8.58165112, 10.95577161, 11.65838488,  9.33993939],
       [11.08380651,  8.999266  , 10.89282043, 12.00728335],
       [10.21655909, 11.45530853, 12.54977348,  8.21833179],
       [10.30755887, 10.05223773,  8.08830097,  9.66286221],
       [10.83263282,  9.33789471,  9.67792345,  8.5931214 ]])

In [14]:
stud_2nd = [18,19,20,20,20,19,18,18,18,20,20]

In [34]:
np.random.randint(18,21,(500))

array([20, 18, 18, 19, 19, 20, 18, 20, 20, 18, 20, 20, 19, 20, 20, 20, 19,
       18, 20, 19, 19, 18, 19, 20, 20, 19, 20, 19, 19, 20, 18, 20, 19, 20,
       19, 19, 18, 20, 19, 19, 18, 20, 19, 19, 20, 20, 19, 19, 19, 19, 18,
       18, 19, 19, 18, 20, 20, 18, 20, 20, 19, 19, 20, 19, 19, 19, 20, 19,
       20, 20, 18, 20, 20, 18, 19, 20, 19, 20, 18, 18, 20, 19, 20, 20, 20,
       18, 18, 18, 20, 18, 18, 19, 18, 20, 18, 19, 19, 20, 18, 19, 18, 18,
       18, 19, 20, 19, 20, 19, 19, 20, 20, 18, 18, 18, 20, 20, 20, 18, 20,
       20, 18, 18, 18, 19, 18, 20, 20, 19, 18, 18, 19, 18, 19, 19, 18, 19,
       18, 20, 20, 19, 18, 20, 18, 20, 18, 18, 18, 18, 18, 18, 18, 19, 19,
       19, 18, 18, 20, 18, 18, 18, 19, 19, 18, 18, 19, 19, 18, 19, 20, 18,
       20, 20, 20, 18, 19, 18, 19, 19, 19, 19, 19, 19, 20, 19, 20, 20, 18,
       19, 20, 20, 19, 18, 19, 20, 19, 19, 19, 18, 18, 18, 18, 19, 19, 18,
       18, 19, 20, 20, 20, 19, 18, 19, 19, 19, 20, 19, 20, 19, 19, 18, 18,
       18, 19, 20, 18, 18

In [36]:
np.random.normal(35,10,500)

array([40.7364392 , 20.69391155, 49.47385141, 34.36481776, 44.12535845,
       33.4531216 , 17.78021896, 32.92839533, 28.40965269, 41.50494024,
       31.63310377, 31.77715001, 30.20291418, 33.14280033, 31.44131901,
       29.98831664, 51.50150433, 37.24784446, 30.04459634, 29.12978437,
       39.34131677, 33.54014291, 31.4273793 , 47.9885896 , 54.89722418,
       36.79406534, 53.03675526, 37.48905123, 40.22793538, 26.21390366,
       35.72431652, 20.65956043, 45.39406062, 24.01659106, 39.51620948,
       40.55533026, 25.6362853 , 26.86549535, 16.73224376, 34.43980258,
       50.70910063, 44.8376621 , 36.22210017, 24.32386562, 39.93843209,
       27.76884925, 36.61848354, 36.54457145, 48.40192667, 47.62258279,
       21.4799239 , 51.61194562, 33.57281061, 38.39465214, 28.3872965 ,
       25.9773666 , 42.72243701, 39.24240984, 28.73191   , 21.03997996,
       32.09997609, 42.50350673, 51.60092304, 29.95696388, 23.20456159,
       24.31674316, 38.58575372, 30.51376372, 32.31309145, 28.48

In [12]:
import numpy as np
tenth_std = np.random.randint(15,18,(1000))
tenth_std

array([16, 15, 16, 17, 17, 16, 15, 16, 17, 17, 17, 16, 17, 16, 16, 16, 15,
       17, 16, 17, 16, 15, 17, 16, 15, 15, 15, 17, 16, 16, 15, 15, 17, 16,
       15, 15, 16, 15, 17, 17, 16, 15, 15, 16, 16, 17, 15, 16, 16, 15, 17,
       16, 15, 16, 16, 15, 17, 16, 17, 17, 17, 15, 15, 16, 17, 15, 15, 15,
       15, 16, 17, 17, 17, 15, 15, 17, 16, 15, 16, 15, 17, 15, 16, 17, 15,
       17, 15, 15, 15, 16, 15, 16, 16, 16, 16, 16, 16, 15, 16, 17, 15, 15,
       17, 16, 17, 15, 16, 17, 16, 15, 16, 17, 16, 16, 16, 16, 17, 15, 16,
       15, 16, 15, 15, 16, 16, 15, 15, 15, 17, 17, 16, 17, 15, 16, 17, 16,
       15, 16, 16, 16, 15, 17, 16, 15, 16, 16, 16, 16, 17, 16, 17, 17, 17,
       15, 17, 15, 16, 17, 15, 15, 15, 15, 16, 15, 16, 17, 16, 15, 16, 16,
       17, 17, 15, 16, 17, 17, 17, 17, 15, 16, 16, 16, 16, 16, 17, 17, 15,
       16, 15, 17, 16, 17, 17, 15, 17, 17, 16, 16, 17, 15, 16, 15, 15, 15,
       15, 17, 17, 16, 15, 16, 15, 17, 15, 17, 17, 15, 16, 15, 15, 16, 15,
       15, 15, 15, 17, 15