In [1]:
import numpy as np

In [2]:
j=[5,7,2,8,4,7]
j

[5, 7, 2, 8, 4, 7]

In [3]:
d=np.array(j)
d

array([5, 7, 2, 8, 4, 7])

In [4]:
type(d)

numpy.ndarray

In [5]:
tuple(j)

(5, 7, 2, 8, 4, 7)

In [6]:
d.shape

(6,)

In [7]:
d.ndim

1

In [8]:
d.size

6

In [9]:
h=d.reshape(2,3)
h

array([[5, 7, 2],
       [8, 4, 7]])

In [10]:
h.size

6

In [11]:
h.shape

(2, 3)

In [12]:
h.ndim

2

In [13]:
s=[[4,8,90,12],[56,78,54,20],[67,89,50,49],[77,88,22,55],[90,40,70,60]]
s

[[4, 8, 90, 12],
 [56, 78, 54, 20],
 [67, 89, 50, 49],
 [77, 88, 22, 55],
 [90, 40, 70, 60]]

In [14]:
type(s)

list

In [15]:
import numpy as np

In [16]:
arr1=np.array(s)
arr1

array([[ 4,  8, 90, 12],
       [56, 78, 54, 20],
       [67, 89, 50, 49],
       [77, 88, 22, 55],
       [90, 40, 70, 60]])

In [17]:
arr1.shape

(5, 4)

In [18]:
arr1.size

20

In [19]:
arr1.ndim

2

In [20]:
k=arr1.reshape(2,2,5)
k

array([[[ 4,  8, 90, 12, 56],
        [78, 54, 20, 67, 89]],

       [[50, 49, 77, 88, 22],
        [55, 90, 40, 70, 60]]])

In [21]:
k.size

20

In [22]:
k.ndim

3

In [23]:
k.shape

(2, 2, 5)

In [24]:
arr1

array([[ 4,  8, 90, 12],
       [56, 78, 54, 20],
       [67, 89, 50, 49],
       [77, 88, 22, 55],
       [90, 40, 70, 60]])

In [25]:
y=arr1.reshape(20,)
y

array([ 4,  8, 90, 12, 56, 78, 54, 20, 67, 89, 50, 49, 77, 88, 22, 55, 90,
       40, 70, 60])

In [26]:
y.ndim

1

In [27]:
z=arr1.reshape(1,20)
z

array([[ 4,  8, 90, 12, 56, 78, 54, 20, 67, 89, 50, 49, 77, 88, 22, 55,
        90, 40, 70, 60]])

In [28]:
z.ndim

2

In [29]:
arr1.shape

(5, 4)

In [30]:
arr1.reshape(2,2,5,1)

array([[[[ 4],
         [ 8],
         [90],
         [12],
         [56]],

        [[78],
         [54],
         [20],
         [67],
         [89]]],


       [[[50],
         [49],
         [77],
         [88],
         [22]],

        [[55],
         [90],
         [40],
         [70],
         [60]]]])

In [31]:
range(5,20)

range(5, 20)

In [32]:
m=[3,4,5,6,7,8]
m

[3, 4, 5, 6, 7, 8]

In [33]:
range(3,101)

range(3, 101)

In [34]:
list(range(3,13,2))

[3, 5, 7, 9, 11]

In [35]:
tuple(range(3,13,2))

(3, 5, 7, 9, 11)

In [36]:
list(range(-1,-10,-1))

[-1, -2, -3, -4, -5, -6, -7, -8, -9]

In [37]:
list(range(10,-10,-2))

[10, 8, 6, 4, 2, 0, -2, -4, -6, -8]

In [38]:
np.arange(2.5,5,0.5)

array([2.5, 3. , 3.5, 4. , 4.5])

In [39]:
np.arange(5,10,1)

array([5, 6, 7, 8, 9])

In [40]:
range(5,50,5)

range(5, 50, 5)

In [41]:
for i in range(5,50,5):
    print('Data',i)

Data 5
Data 10
Data 15
Data 20
Data 25
Data 30
Data 35
Data 40
Data 45


In [42]:
j=[5,87,23,46,62,84,80,45,77,33,80]
j

[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]

In [43]:
range(len(j))

range(0, 11)

In [44]:
for i in range(len(j)):
    print(i)

0
1
2
3
4
5
6
7
8
9
10


In [45]:
j[0:11:2]

[5, 23, 62, 80, 77, 80]

In [46]:
j[1:11:2]

[87, 46, 84, 45, 33]

In [47]:
y=[]
x=[]
for i in range(len(j)):
    if i%2==0:
        x.append(j[i])
    else:
        y.append(j[i])

In [48]:
y

[87, 46, 84, 45, 33]

In [49]:
x

[5, 23, 62, 80, 77, 80]

In [50]:
for i in j:
    print(i)

5
87
23
46
62
84
80
45
77
33
80


In [51]:
import numpy as np

In [53]:
d=np.array([10,40,50,30,70])
d

array([10, 40, 50, 30, 70])

In [61]:
np.mean(d)

40.0

In [56]:
np.median(d)

40.0

In [58]:
np.var(d)

400.0

In [59]:
np.std(d)

20.0

In [60]:
np.max(d)

70

In [62]:
np.min(d)

10

In [68]:
q1=np.quantile(d,0.25)
q1

30.0

In [69]:
q2=np.quantile(d,0.5)
q2

40.0

In [70]:
q3=np.quantile(d,0.75)
q3

50.0

In [76]:
r=np.random.rand(10,5)
r

array([[0.25152693, 0.81185575, 0.36862579, 0.33132564, 0.92096105],
       [0.70163841, 0.88310976, 0.24312529, 0.03724871, 0.30479013],
       [0.85858484, 0.80079148, 0.35115474, 0.21066566, 0.6879644 ],
       [0.47997032, 0.74378096, 0.90508056, 0.02652386, 0.62691467],
       [0.59880609, 0.8404836 , 0.96976096, 0.53348855, 0.92728299],
       [0.4374244 , 0.21881257, 0.32703731, 0.19356074, 0.26312792],
       [0.91405373, 0.41711107, 0.1869319 , 0.29021622, 0.63061263],
       [0.02632034, 0.16779811, 0.16154092, 0.57406511, 0.16647569],
       [0.33001206, 0.14086849, 0.50043521, 0.07236088, 0.26720031],
       [0.29419405, 0.60788475, 0.82197352, 0.95179863, 0.8965967 ]])

In [77]:
r.size

50

In [78]:
r.ndim

2

In [99]:
s=np.random.rand(5,3,2) # 0 to 1 
s

array([[[0.38245253, 0.80045137],
        [0.48575674, 0.18927981],
        [0.11892037, 0.06806254]],

       [[0.66110879, 0.91458277],
        [0.60069013, 0.17511575],
        [0.9146614 , 0.74190315]],

       [[0.85078096, 0.64539198],
        [0.96731412, 0.59676519],
        [0.04029439, 0.89023454]],

       [[0.62743097, 0.07288768],
        [0.5672723 , 0.00499873],
        [0.03019992, 0.42871884]],

       [[0.9132208 , 0.24135375],
        [0.64417676, 0.22790424],
        [0.78289497, 0.39289769]]])

In [96]:
t=np.random.rand(1)
t

array([0.78613363])

In [94]:
s.ndim

3

In [97]:
t.ndim

1

In [98]:
np.random.randn(30,1)

array([[-0.06033325],
       [-0.68466974],
       [ 0.44796436],
       [-1.10755268],
       [ 1.07729191],
       [ 2.14693548],
       [-0.83869364],
       [-1.14302863],
       [ 0.4776558 ],
       [-0.30327636],
       [ 1.95221194],
       [-0.6930061 ],
       [ 0.74891531],
       [ 1.57165714],
       [ 1.20365689],
       [-0.82230971],
       [ 0.00402435],
       [ 0.15200959],
       [ 0.8696466 ],
       [-0.58273586],
       [ 0.65312878],
       [-1.40067618],
       [-0.02430774],
       [ 1.06639294],
       [ 0.37901131],
       [-0.63387581],
       [-1.14476027],
       [ 0.26470744],
       [-1.10551714],
       [ 0.36960798]])

In [100]:
np.random.normal(10,2,(4,5))

array([[11.64334729, 10.83736698,  9.29352986,  8.32264135, 10.4878028 ],
       [11.15544312,  9.72852142, 13.7291226 ,  8.56127829, 10.83646777],
       [ 9.89213767,  8.49249092, 10.05485412, 10.01322921,  9.42095239],
       [11.02465341, 12.33942876, 11.63415435,  5.93072617, 14.80318252]])

In [108]:
np.random.randint(35,86,(5,5))

array([[70, 74, 61, 42, 67],
       [74, 47, 53, 70, 51],
       [82, 81, 76, 62, 81],
       [78, 69, 37, 73, 47],
       [76, 59, 40, 85, 79]])