In [1]:
import numpy as np

In [7]:
a=np.random.randint(33,99,20)
a

array([72, 67, 43, 69, 79, 43, 93, 38, 52, 68, 65, 83, 95, 89, 59, 41, 98,
       84, 84, 81])

In [9]:
a[-1]

81

In [11]:
a[19]

81

In [47]:
b=np.random.randint(30,99,(8,9))
b

array([[89, 37, 56, 85, 57, 77, 60, 95, 30],
       [54, 86, 66, 77, 30, 67, 34, 51, 82],
       [95, 43, 81, 50, 58, 95, 47, 91, 61],
       [68, 67, 91, 56, 45, 57, 71, 94, 96],
       [81, 51, 62, 31, 49, 78, 62, 72, 52],
       [96, 30, 54, 76, 46, 30, 70, 32, 74],
       [38, 96, 61, 35, 93, 81, 48, 61, 71],
       [53, 69, 65, 90, 42, 74, 87, 85, 72]])

In [49]:
b.shape

(8, 9)

In [51]:
b.ndim

2

In [53]:
b[7,0]

53

### array[row_start: row_end: row_step, col_start: col_end: col_step]

In [55]:
b[2:6]

array([[95, 43, 81, 50, 58, 95, 47, 91, 61],
       [68, 67, 91, 56, 45, 57, 71, 94, 96],
       [81, 51, 62, 31, 49, 78, 62, 72, 52],
       [96, 30, 54, 76, 46, 30, 70, 32, 74]])

In [61]:
b[2:6:2,1:7:2]

array([[43, 50, 95],
       [51, 31, 78]])

In [63]:
b[1:5,1:6]

array([[86, 66, 77, 30, 67],
       [43, 81, 50, 58, 95],
       [67, 91, 56, 45, 57],
       [51, 62, 31, 49, 78]])

In [66]:
import pandas as pd

In [122]:
k=[[4,7],[2,9],[90,50]]
k

[[4, 7], [2, 9], [90, 50]]

In [124]:
np.array(k)

array([[ 4,  7],
       [ 2,  9],
       [90, 50]])

In [126]:
t=np.array(k)
t

array([[ 4,  7],
       [ 2,  9],
       [90, 50]])

In [128]:
t.ndim

2

In [130]:
pd.Series(t)

ValueError: Data must be 1-dimensional, got ndarray of shape (3, 2) instead

In [132]:
pd.DataFrame(t)

0   1
0   4   7
1   2   9
2  90  50

In [137]:
pd.DataFrame(k,columns=['name','sub'],index=[289,300,389])

name  sub
289     4    7
300     2    9
389    90   50

In [141]:
df['sub'].mean()

NameError: name 'df' is not defined